# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# MakeCrimeLayers.py
# Created on: 2015-09-03 12:42:20.00000
#   (generated by ArcGIS/ModelBuilder)
# Description:
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy, os

def replaceSpecialCharacters(string):
    ch = [' ','!','@','#','$','%','^','&','*','(',')','<','>','/']
    for c in ch:
        string = str(string).replace(c,'_')

    return string

def parseCommandUnit(string):
    value = str(string).split(" ")
    elements = len(value)
    unit = ""

    if elements == 1:  # e.g., "RTU"
        command = "%s" % (" ".join(value[0:2]))
    elif elements == 2:  # e.g., "1-1 CAV"
        command = "%s" % (" ".join(value[0:2]))
    elif elements == 3:  # e.g., "1-1 CAV MORTAR"
        command = "%s" % (" ".join(value[0:2]))
        unit = "%s" % (value[2])
    elif elements == 4:  # e.g., "1-1 CAV A CO"
        command = "%s" % (" ".join(value[0:2]))
        unit = "%s" % (" ".join(value[2:4]))
    elif elements == 5:  #
        command = "%s" % (" ".join(value[0:2]))
        unit = "%s, %s" % (" ".join(value[2:4])," ".join(value[4:5]))
    elif elements == 6:  # e.g., "1-1 CAV A CO 1 PLT"
        command = "%s" % (" ".join(value[0:2]))
        unit = "%s, %s" % (" ".join(value[2:4])," ".join(value[4:6]))
    else:
        command = "%s" % (value)
        unit = ""

    return command, unit

##
##
# ### Local variables:
### set-up map document and data frame info
lyr = arcpy.GetParameter(0)
the_field = arcpy.GetParameterAsText(1)


mxd = arcpy.mapping.MapDocument("CURRENT")
df = mxd.activeDataFrame

output = set()

#expression = '"%s" IS NOT NULL' % (the_field)
arcpy.AddMessage("Opening Cursor with: %s as lyr and %s as field." % (lyr.name, the_field))
cursor = arcpy.da.SearchCursor(lyr,the_field)
for row in cursor:
    output.add(row[0])
del cursor

mylist = sorted(list(set(output)))
for l in mylist:
    arcpy.AddMessage(parseCommandUnit(l))
