# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# arcpy_getFeatureSet.py
# Created on: 2017-01-26 13:39:20.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: arcpy_getFeatureSet <Feature_Set> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
Feature_Set = arcpy.GetParameterAsText(0)
if Feature_Set == '#' or not Feature_Set:
    Feature_Set = "in_memory\\{A490B042-2F36-425A-A0B3-D21EFBE60612}" # provide a default value if unspecified

# Local variables:
selected_location = "in_memory\\selected_location"

# Process: Select
arcpy.Select_analysis(Feature_Set, selected_location, "")

