# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# arcpy_Append_Example.py
# Created on: 2017-02-13 14:18:40.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Set the necessary product code
# import arcinfo


# Import arcpy module
import arcpy


# Local variables:
tmp_BufLYR = "tmp_BufLYR"
location_coordinate_buffers__4_ = tmp_BufLYR
location_coordinate_buffers = "location_coordinate_buffers"
location_coordinate_buffers__2_ = location_coordinate_buffers
location_coordinate_buffers_ = "C:\\Users\\chrism\\Documents\\ArcGIS\\Default.gdb\\location_coordinate_buffers_"

# Process: Truncate Table
arcpy.TruncateTable_management(location_coordinate_buffers)

# Process: Append
arcpy.Append_management("tmp_BufLYR", location_coordinate_buffers__2_, "NO_TEST", "LOCCRD_SEQ_NR_FK \"LOCCRD_SEQ_NR_FK\" true false false 4 Long 0 0 ,First,#,tmp_BufLYR,LOCCRD_SEQ_NR_FK,-1,-1;ACCURACY_LVL_CD \"ACCURACY_LVL_CD\" true true false 2 Text 0 0 ,First,#,tmp_BufLYR,ACCURACY_LVL_CD,-1,-1;CREATED_BY \"CREATED_BY\" true true false 20 Text 0 0 ,First,#,tmp_BufLYR,CREATED_BY,-1,-1;CREATED_DATE \"CREATED_DATE\" true true false 8 Date 0 0 ,First,#,tmp_BufLYR,CREATED_DATE,-1,-1;LAST_MODIFIED_BY \"LAST_MODIFIED_BY\" true true false 20 Text 0 0 ,First,#,tmp_BufLYR,LAST_MODIFIED_BY,-1,-1;LAST_MODIFIED_DATE \"LAST_MODIFIED_DATE\" true true false 8 Date 0 0 ,First,#,tmp_BufLYR,LAST_MODIFIED_DATE,-1,-1;LOCCRD_SEQ_NR \"LOCCRD_SEQ_NR\" true true false 4 Long 0 0 ,First,#,tmp_BufLYR,LOCCRD_SEQ_NR,-1,-1;SHAPE_Length \"SHAPE_Length\" false true true 8 Double 0 0 ,First,#,tmp_BufLYR,SHAPE_Length,-1,-1;SHAPE_Area \"SHAPE_Area\" false true true 8 Double 0 0 ,First,#,tmp_BufLYR,SHAPE_Area,-1,-1", "")

# Process: Find Identical
arcpy.FindIdentical_management(location_coordinate_buffers__4_, location_coordinate_buffers_, "LOCCRD_SEQ_NR_FK;LOCCRD_SEQ_NR", "", "0", "ALL")

