# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# arcpy_getCount.py
# Created on: 2019-12-12 14:56:17.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
Projects = "Projects"
Row_Count = "0"

# Process: Get Count
arcpy.GetCount_management(Projects)

