# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# arcpy_CalculateFieldEg.py
# Created on: 2017-03-29 11:21:49.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
location_coord_areas = "location_coord_areas"
location_coord_areas__2_ = location_coord_areas

# Process: Calculate Field
arcpy.CalculateField_management(location_coord_areas, "featureName", "\"BUFFER_POLYGON\"", "VB", "")

