# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# arcpy_AddJoinExample.py
# Created on: 2017-02-13 14:58:48.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy


# Local variables:
findIdent_tbl = "findIdent_tbl"
findIdent_tbl__2_ = findIdent_tbl
location_coordinate_buffers = "location_coordinate_buffers"

# Process: Add Join
arcpy.AddJoin_management(findIdent_tbl, "IN_FID", location_coordinate_buffers, "OBJECTID", "KEEP_ALL")

