# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# cm_selectFeatureForRowCount.py
# Created on: 2019-12-12 11:33:22.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: cm_selectFeatureForRowCount <Selecting_Features> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
Selecting_Features = arcpy.GetParameterAsText(0)
if Selecting_Features == '#' or not Selecting_Features:
    Selecting_Features = "in_memory\\{6255121D-19A7-4954-9C94-6F5CCC932B6F}" # provide a default value if unspecified

# Local variables:
Projects = "Projects"
Projects__2_ = Projects
Row_Count = "0"

# Process: Select Layer By Location
arcpy.SelectLayerByLocation_management(Projects, "INTERSECT", Selecting_Features, "5 Meters", "NEW_SELECTION", "NOT_INVERT")

# Process: Get Count
arcpy.GetCount_management(Projects__2_)

