# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# scratch.py
# Created on: 2014-10-29 15:00:34.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: scratch <Workspace> <Folder> <Multiple_Value> 
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
Workspace = arcpy.GetParameterAsText(0)

Folder = arcpy.GetParameterAsText(1)

Multiple_Value = arcpy.GetParameterAsText(2)

# Local variables:

